"""Python beginner lessons (L1-L15). Same content as Phase 2, extracted to its own module."""

LESSONS_PYTHON_BEGINNER = [
    {"id": 1, "topic": "Say hello with print()",
     "content": "<b>Lesson 1 — Say hello with print()</b>\n\nIn Python, <code>print()</code> shows text on screen.\nThink of it like a loudspeaker for your program.\n\n<b>Example:</b>\n<pre>print(\"Hello, world!\")</pre>\nThis shows: <code>Hello, world!</code>\n\n<b>Your turn:</b>\nWrite one line that prints a sentence with your name.\nExample: <pre>print(\"My name is Sara\")</pre>\n\nSend me your code. 👇",
     "exercise": "Write a print() statement that shows a sentence with your name.",
     "rubric": "Pass if: code contains print() with a string inside. Any working print passes. Fail only if print() is missing or has a syntax error.",
     "concepts": ["print"]},
    {"id": 2, "topic": "Storing things in variables",
     "content": "<b>Lesson 2 — Storing things in variables</b>\n\nA <b>variable</b> is like a labelled box.\n\n<b>Example:</b>\n<pre>age = 25\nprint(age)</pre>\nShows: <code>25</code>\n\nYou can store text too:\n<pre>city = \"Addis Ababa\"\nprint(city)</pre>\n\n<b>Your turn:</b>\nCreate a variable called <code>fav</code> with your favourite number, then print it.\n<pre>fav = 7\nprint(\"My favourite number is\", fav)</pre>\n\nSend me your code. 👇",
     "exercise": "Store a number in `fav` and print a sentence with it.",
     "rubric": "Pass if: `fav` is assigned a number and print() shows it. Accept any format.",
     "concepts": ["variables", "print"]},
    {"id": 3, "topic": "Doing math",
     "content": "<b>Lesson 3 — Doing math</b>\n\nPython is a calculator! Use <code>+ - * /</code>\n\n<b>Example:</b>\n<pre>price = 100\ntax = price * 0.15\ntotal = price + tax\nprint(\"Total:\", total)</pre>\n\n<b>Your turn:</b>\nCalculate the area of a rectangle:\n<pre>width = 5\nheight = 3\narea = width * height\nprint(\"Area:\", area)</pre>\n\nPick your own numbers. Send me your code. 👇",
     "exercise": "Create width and height variables, multiply them into area, and print.",
     "rubric": "Pass if: two number variables are multiplied and the result is printed.",
     "concepts": ["variables", "math", "print"]},
    {"id": 4, "topic": "Making decisions with if/else",
     "content": "<b>Lesson 4 — Making decisions with if/else</b>\n\n\"<i>If it's raining, take an umbrella. Otherwise, sunglasses.</i>\"\n\n<b>Example:</b>\n<pre>weather = \"rainy\"\n\nif weather == \"rainy\":\n    print(\"Take an umbrella\")\nelse:\n    print(\"Wear sunglasses\")</pre>\n\n<code>==</code> means \"is equal to?\" (two equals signs)\n\n<b>Your turn:</b>\nCreate <code>score</code> with a number. If 50 or more, print <code>You passed!</code>. Otherwise <code>Try again</code>.\n<pre>score = 75\n\nif score >= 50:\n    print(\"You passed!\")\nelse:\n    print(\"Try again\")</pre>\n\nSend me your code. 👇",
     "exercise": "Create `score`, if >= 50 print pass message, else print fail message.",
     "rubric": "Pass if: variable with number, if with comparison, else. Both branches print. Accept any messages.",
     "concepts": ["if/else", "comparison"]},
    {"id": 5, "topic": "Asking the user for input",
     "content": "<b>Lesson 5 — Asking the user for input</b>\n\n<code>input()</code> asks a question and waits for an answer.\n\n<b>Example:</b>\n<pre>name = input(\"What is your name? \")\nprint(\"Hello\", name)</pre>\n\n<b>Your turn:</b>\nAsk for the user's name with <code>input()</code> and print a greeting.\n<pre>name = input(\"Your name? \")\nprint(\"Welcome,\", name)</pre>\n\nSend me your code. 👇",
     "exercise": "Use input() to get a name and print a greeting with it.",
     "rubric": "Pass if: input() is called, result stored in variable, print uses it. Accept any greeting.",
     "concepts": ["input", "variables", "print"]},
    {"id": 6, "topic": "Checking multiple conditions",
     "content": "<b>Lesson 6 — Checking multiple conditions with elif</b>\n\nWhen you have more than two choices, use <code>elif</code>.\n\n<b>Example:</b>\n<pre>temp = 35\n\nif temp > 30:\n    print(\"Hot!\")\nelif temp > 20:\n    print(\"Nice\")\nelse:\n    print(\"Cold\")</pre>\n\n<b>Your turn:</b>\nCreate <code>grade</code> (0-100). Print \"Excellent\" if 90+, \"Good\" if 70+, \"Keep trying\" otherwise.\n<pre>grade = 85\n\nif grade >= 90:\n    print(\"Excellent\")\nelif grade >= 70:\n    print(\"Good\")\nelse:\n    print(\"Keep trying\")</pre>\n\nSend me your code. 👇",
     "exercise": "Create `grade`, use if/elif/else for Excellent/Good/Keep trying.",
     "rubric": "Pass if: number variable, if, at least one elif, else, each with print.",
     "concepts": ["if/elif/else", "comparison"]},
    {"id": 7, "topic": "Repeating with for loops",
     "content": "<b>Lesson 7 — Repeating with for loops</b>\n\nA <b>loop</b> runs code for each item in a group.\n\n<b>Example:</b>\n<pre>fruits = [\"apple\", \"banana\", \"mango\"]\n\nfor fruit in fruits:\n    print(fruit)</pre>\n\n<b>Your turn:</b>\nCreate a list of 3 things you like and loop through them.\n<pre>colors = [\"red\", \"blue\", \"green\"]\n\nfor color in colors:\n    print(color)</pre>\n\nSend me your code. 👇",
     "exercise": "Create a list with 3+ items and use a for loop to print each.",
     "rubric": "Pass if: list with 2+ items and a for loop that prints each.",
     "concepts": ["lists", "for loop"]},
    {"id": 8, "topic": "Counting with range()",
     "content": "<b>Lesson 8 — Counting with range()</b>\n\n<code>range(n)</code> gives numbers 0 to n-1.\n\n<b>Example:</b>\n<pre>for i in range(5):\n    print(i)</pre>\n<code>range(1, 6)</code> starts at 1: <code>1, 2, 3, 4, 5</code>\n\n<b>Your turn:</b>\nPrint numbers 1 through 10.\n<pre>for i in range(1, 11):\n    print(i)</pre>\n\nSend me your code. 👇",
     "exercise": "Use a for loop with range() to print numbers 1 through 10.",
     "rubric": "Pass if: a for loop uses range() and prints numbers 1-10. Accept any approach.",
     "concepts": ["for loop", "range"]},
    {"id": 9, "topic": "Adding to a list",
     "content": "<b>Lesson 9 — Adding to a list</b>\n\nLists can grow. Use <code>.append()</code>.\n\n<b>Example:</b>\n<pre>shopping = []\nshopping.append(\"bread\")\nshopping.append(\"milk\")\nprint(shopping)</pre>\n\n<b>Your turn:</b>\nStart with an empty list. Add 3 items with <code>.append()</code>, then print.\n\nSend me your code. 👇",
     "exercise": "Start with empty list, append 3 items, print.",
     "rubric": "Pass if: list created, .append() called 2+ times, list printed.",
     "concepts": ["lists", "append"]},
    {"id": 10, "topic": "Your first function",
     "content": "<b>Lesson 10 — Your first function</b>\n\nA <b>function</b> is a reusable recipe.\n\n<b>Example:</b>\n<pre>def greet(name):\n    print(\"Hello\", name)\n\ngreet(\"Sara\")\ngreet(\"David\")</pre>\n\n<b>Your turn:</b>\nWrite <code>double(n)</code> that prints n * 2, then call it.\n<pre>def double(n):\n    print(n * 2)\n\ndouble(5)</pre>\n\nSend me your code. 👇",
     "exercise": "Write function double(n) that prints n*2. Call it.",
     "rubric": "Pass if: `def double(` exists, prints or returns n*2, and is called.",
     "concepts": ["functions", "def"]},
    {"id": 11, "topic": "Functions that give back a value",
     "content": "<b>Lesson 11 — Functions that return</b>\n\n<code>return</code> sends a result back.\n\n<b>Example:</b>\n<pre>def add(a, b):\n    return a + b\n\nresult = add(3, 4)\nprint(result)  # 7</pre>\n\n<b>Your turn:</b>\nWrite <code>square(n)</code> that <b>returns</b> n * n. Print the result.\n<pre>def square(n):\n    return n * n\n\nprint(square(5))</pre>\n\nSend me your code. 👇",
     "exercise": "Write square(n) returning n*n. Print result.",
     "rubric": "Pass if: `def square(` with return n*n. Called and printed. Fail if prints inside instead of returning.",
     "concepts": ["functions", "return"]},
    {"id": 12, "topic": "Functions with default values",
     "content": "<b>Lesson 12 — Default values</b>\n\nParameters can have defaults:\n\n<pre>def power(base, exp=2):\n    return base ** exp\n\nprint(power(3))     # 9\nprint(power(2, 3))  # 8</pre>\n\n<b>Your turn:</b>\nWrite <code>power(base, exp=2)</code> returning base ** exp. Call with and without exp.\n\nSend me your code. 👇",
     "exercise": "Write power(base, exp=2) returning base**exp. Call both ways.",
     "rubric": "Pass if: def power with default exp=2, returns base**exp, called at least once.",
     "concepts": ["functions", "default parameters", "return"]},
    {"id": 13, "topic": "Working with text (strings)",
     "content": "<b>Lesson 13 — Working with text</b>\n\n<pre>msg = \"hello world\"\nprint(msg.upper())        # HELLO WORLD\nprint(msg.replace(\"world\", \"Python\"))\nprint(len(msg))              # 11</pre>\n\n<b>Your turn:</b>\nCreate a string, print it in uppercase, and print its length.\n<pre>text = \"python is fun\"\nprint(text.upper())\nprint(len(text))</pre>\n\nSend me your code. 👇",
     "exercise": "Create a string, print uppercase with .upper(), print length with len().",
     "rubric": "Pass if: string exists, .upper() called and printed, len() used.",
     "concepts": ["strings", "upper", "len"]},
    {"id": 14, "topic": "Building a small program",
     "content": "<b>Lesson 14 — Building a calculator</b>\n\n<pre>def calculate(a, b, op):\n    if op == \"+\":\n        return a + b\n    elif op == \"-\":\n        return a - b\n    else:\n        return \"Unknown\"\n\nprint(calculate(10, 3, \"+\"))\nprint(calculate(10, 3, \"-\"))</pre>\n\n<b>Your turn:</b>\nAdd * and / operations. Call with each.\n\nSend me your code. 👇",
     "exercise": "Write calculate(a, b, op) handling +, -, *, /. Call with 2+ operations.",
     "rubric": "Pass if: function handles 3+ operations with if/elif, returns results, and is called.",
     "concepts": ["functions", "if/elif", "math"]},
    {"id": 15, "topic": "FizzBuzz!",
     "content": "<b>Lesson 15 — FizzBuzz!</b>\n\nThe famous challenge:\n- Numbers 1-20\n- Divisible by 3: Fizz\n- Divisible by 5: Buzz\n- Both: FizzBuzz\n\n<b>Start:</b>\n<pre>for i in range(1, 21):\n    if i % 15 == 0:\n        print(\"FizzBuzz\")\n    elif i % 3 == 0:\n        print(\"Fizz\")\n    elif ...  # finish it!</pre>\n\nSend me your code. 👇",
     "exercise": "FizzBuzz for 1-20.",
     "rubric": "Pass if: loop, modulo 3 and 5, FizzBuzz for combined (15 or both), prints correctly.",
     "concepts": ["loops", "if/elif/else", "modulo"]},
]
